CREATE TABLE Usuario (
    id BIGINT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    imageid BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (imageid) REFERENCES Image(id)
);
